project:
  render:
    - content/*.fr.qmd
    - content/*/*.fr.qmd
    - content/*/*/*.fr.qmd
    - content/*/*/*/*.fr.qmd
    - content/*/*/*/*.ipynb
    - "!content/*.en.qmd"
    - "!content/*/*.en.qmd"
    - "!content/*/*/*.en.qmd"
    - "!content/*/*/*/*.en.qmd"
    - "!redirect.qmd"
    - "!404.qmd"
  output-dir: _site/fr

lang: fr

website:
  title: "Mon Site Web"
  navbar:
    left:
      - href: content/index.fr.qmd
      - href: content/cv.fr.qmd
      - href: content/blogs/index.fr.qmd
    right:
      - href: ../en/content/{{< meta filename >}}.html
        text: English