project:
  type: website
  output-dir: _site

projects:
  - en
  - fr
  - ru

website:
  title: "Serge Goussev"
  repo-url: https://github.com/sergegoussev/sergegoussev.github.io
  repo-actions: [source]
  bread-crumbs: true
  page-navigation: true
  back-to-top-navigation: true
  search: true
  draft-mode: visible
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
    right:
      - text: Languages
        menu:
          - text: English
            href: "en/index.html"
          - text: Français
            href: "fr/index.html"
          - text: Русский
            href: "ru/index.html"

execute:
  freeze: auto

format:
  html:
    toc: true
    theme: 
      light: flatly
      dark: cyborg
