project:
  render:
    - content/*.en.qmd
    - content/*/*.en.qmd
    - content/*/*/*.en.qmd
    - content/*/*/*/*.en.qmd
    - content/*/*/*/*.ipynb
    - "!content/*.fr.qmd"
    - "!content/*/*.fr.qmd"
    - "!content/*/*/*.fr.qmd"
    - "!content/*/*/*/*.fr.qmd"
    - "!redirect.qmd"
    - "!404.qmd"
  output-dir: _site/en 

lang: en

website:
  title: "My Website"
  navbar:
    left:
      - href: content/index.en.qmd
      - href: content/cv.en.qmd
      - href: content/blogs/index.en.qmd
    right:
      - href: ../fr/content/{{< meta filename >}}.html
        text: Fran√ßais
