project:
  type: website
  output-dir: _site/
  resources:
    - index.html


website:
  title: "Serge Goussev"
  repo-url: https://github.com/sergegoussev/sergegoussev.github.io
  repo-actions: [source]
  bread-crumbs: true
  page-navigation: true
  back-to-top-navigation: true
  search: true
  draft-mode: visible

format:
  html:
    toc: true
    theme: 
      light: flatly
      dark: cyborg