project:
  render:
    - content/
    - "!redirect.qmd"
  output-dir: _site/fr

lang: fr

website:
  title: "Mon Site Web"
  navbar:
    left:
      - href: content/index.qmd
        text: Accueil
      - href: content/cv.qmd
        text: CV
      - href: content/blog.qmd
        text: Blog
    right:
      - href: ../en/content/{{< meta filename >}}.html
        text: English