project:
  output-dir: _site/en 

lang: en

website:
  title: "My Website"
  navbar:
    left:
      - href: content/index.qmd
        text: Home
      - href: content/cv.qmd
        text: CV
      - href: content/blog.qmd
        text: Blog
    right:
      - href: ../fr/index.html 
        text: Fran√ßais
